### PR TITLE
Overhaul to Support Python 3.8 through 3.12 and Modern Dependencies

### LINKED ISSUE #19: ImportError: cannot import name 'Panel' from 'bokeh.models'
Hello!

Thanks for uploading the packaged. I'm currently running on an M1 Mac with python 3.10 and I get this error when loading the tutorial dataset file. 
Any idea why that might be?
Thanks
```
>> bokeh info
Python version      :  3.10.9 (main, Jan 11 2023, 09:18:20) [Clang 14.0.6 ]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
```

### LINKED ISSUE #23: Using similarity type "structural" throws AttributeError if using t-SNE
When using similarity type 'structural' together with t-SNE, an `AttributeError: 'list' object has no attribute 'shape'` is thrown. Code to reproduce the error:

```python
from chemplot import Plotter, load_data

data_BBBP = load_data("BBBP")
cp_BBBP = Plotter.from_smiles(data_BBBP["smiles"], target=data_BBBP["target"], target_type="C", sim_type="structural")
cp_BBBP.tsne()
```

I will be submitting a pull request for a proposed fix shortly.

### LINKED ISSUE #25: Installation issues: matplotlib; sklearn
Hi!

When trying to install with pip, I get errors with the matplotlib and scikit-learn libraries, even though both are installed and up to date.
At the bottom, I paste the fragment of the entire output from the console, where the errors occur. The whole output is attached as a txt file. I have no idea what to do with this problem. I'm using PowerShell with system administrator privileges. RDkit is installed and activated.

[chemplot_install_error.txt](https://github.com/mcsorkun/ChemPlot/files/11652503/chemplot_install_error.txt)

     `Extracting freetype-2.6.1.tar.gz
      Building freetype in build\freetype-2.6.1
      msbuild build\freetype-2.6.1\builds\windows\vc2010\freetype.sln /t:Clean;Build /p:Configuration=Release;Platform=x64
      error: command 'msbuild' failed: None
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for matplotlib`

      error: could not create 'build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-          
      australian-limit-2-data_version-1-status-deactivated.json.gz': No such file or directory
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\aleniak\AppData\Local\Temp\pip-install-1uih_fd0\scikit-learn_a2e09175a0394b6b907b9332707bf76e\build\temp.win-amd64-cpython-310\Release\ccompiler_opt_cache_ext.py
      INFO:
      ########### CLIB COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\aleniak\AppData\Local\Temp\pip-install-1uih_fd0\scikit-learn_a2e09175a0394b6b907b9332707bf76e\build\temp.win-amd64-cpython-310\ccompiler_opt_cache_clib.py
      [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for scikit-learn
    Failed to build matplotlib scikit-learn
    ERROR: Could not build wheels for matplotlib, scikit-learn, which is required to install pyproject.toml-based projects`

### LINKED ISSUE #27: unexpected attribute 'plot_width' to figure,
I get this error.
cp_BACE.interactive_plot(show_plot=True)
Any idea what is the problem?

'''python
{
	"name": "AttributeError",
	"message": "unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 cp_BACE.interactive_plot(show_plot=True)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/chemplot/chemplot.py:542, in Plotter.interactive_plot(self, size, kind, remove_outliers, is_colored, clusters, filename, show_plot, title)
    540 tabs = None
    541 if kind == \"scatter\":
--> 542     p, tabs = self.__interactive_scatter(x, y, df_data, size, is_colored, clusters, title)
    543 else: 
    544     p = self.__interactive_hex(x, y, df_data, size, title)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/chemplot/chemplot.py:626, in Plotter.__interactive_scatter(self, x, y, df_data, size, is_colored, clusters, title)
    623     TOOLTIPS = parameters.TOOLTIPS_TARGET
    625 # Create plot
--> 626 p = figure(title=title, plot_width=size, plot_height=size, tools=tools, tooltips=TOOLTIPS)
    628 if len(self.__target) == 0 or not(is_colored):
    629     p.circle(x=x, y=y, size=2.5, alpha=0.8, source=df_data)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/bokeh/plotting/_figure.py:195, in figure.__init__(self, *arg, **kw)
    193 for name in kw.keys():
    194     if name not in names:
--> 195         self._raise_attribute_error_with_matches(name, names | opts.properties())
    197 super().__init__(*arg, **kw)
    199 self.x_range = get_range(opts.x_range)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/bokeh/core/has_props.py:375, in HasProps._raise_attribute_error_with_matches(self, name, properties)
    372 if not matches:
    373     matches, text = sorted(properties), \"possible\"
--> 375 raise AttributeError(f\"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}\")

AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width"
}
'''

### LINKED ISSUE #28: Google Colab: Pip Install Error
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### PR DESCRIPTION
**Pull request by JacksonBurns**
Hello @mcsorkun and @dajtmullaj thank you for making ChemPlot! I have found it very useful in my work, and wanted to help get it back up and running on modern versions of Python with the latest dependencies.

Here is a summary of the changes in this PR:
 - updates the usage of sklearn, matplotlib, bokeh, etc. to work with their latest versions
 - uses github actions test runner to test against all platforms and modern python versions (you were already doing this in a different way)
 - modernizes and centralizes project metadata to the pyproject file

This PR would resolve the following issues:
 - resolve #23 - the __data_scaler always outputs numpy arrays now
 - resolve #28 - this PR would add support for the versions of Python used in google colab
 - resolve #27 - fixes the API for the latest major version of bokeh
 - resolve #25 - supports all versions of the mentioned dependencies
 - resolve #19 - updates to the new bokeh API which is TabPanel instead of Panel

I am happy to explain any changes I have made to help get this merged. Thank you again for making this tool!

### CODE REVIEW

**Comment by mcsorkun** [comment]
Hello Jackson, 

Thanks for your updates! All looks good for now. We will review and probably merge them tomorrow. We will update you after the review.

**Review by mcsorkun — APPROVED** [review]

**Review by mcsorkun — COMMENTED** [review]
ok

**Comment by JacksonBurns** [comment]
Sounds good @mcsorkun! BTW I have added GitHub actions that run tests for pull requests - if you click 'Approve Workflow' on this PR they will run and show that the tests are passing on the latest Python versions.

**Review by dajtmullaj — APPROVED** [review]

**Comment by mcsorkun** [comment]
@JacksonBurns We reviewed the changes and they look very nice. There are still some points that we did not fully understand. It will be very nice if we can set up a meeting so you can explain the updates. I will contact you over linkedin to set up a meeting.

**Comment by mcsorkun** [comment]
> @JacksonBurns We reviewed the changes and they look very nice. There are still some points that we did not fully understand. It will be very nice if we can set up a meeting so you can explain the updates. I will contact you over linkedin to set up a meeting.

@JacksonBurns Please let me know if you are available today at 17:30  NL time (GMT +2) ?

**Comment by JacksonBurns** [comment]
@mcsorkun I would be happy to, I just messaged you.

**Pull request merged**
